BabyStore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BabyStore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

BabyStore/Pages/Login.cshtml.cs
using BOs.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Identity.Client;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Services;
using Services.Interfaces;
using System.ComponentModel.DataAnnotations;
using System.Net;

namespace BabyStore.Pages
{
    public class AuthenModel : PageModel
    {
        private readonly IUserService _userService;

        public AuthenModel(IUserService userService)
        {
            _userService = userService;
        }

        public class LoginModel
        {
            public string Username { get; set; }
            public string Password { get; set; }
        }

        public class RegisterModel
        {
            public string FullName { get; set; }

            public string Username { get; set; }

            [EmailAddress]
            public string Email { get; set; }

            [Phone]
            public string Phone { get; set; }

            [DataType(DataType.Password)]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            public string Address { get; set; }
        }

        [BindProperty]
        public RegisterModel registerModel { get; set; }

        [BindProperty]
        public LoginModel loginModel { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPostLogin()
        {
            var user = _userService.Login(loginModel.Username, loginModel.Password);
            if (user != null)
            {
                HttpContext.Session.SetString("username", user.FullName);
                HttpContext.Session.SetString("id", user.UserId);
                HttpContext.Session.SetString("email", user.Email);
                HttpContext.Session.SetInt32("role", user.Role);
                HttpContext.Session.SetString("address", user.Address);
                if (user.Status == 0)
                {
                    ViewData["error"] = "Your account has been blocked";
                    return Page();
                }
                else
                {
                    if (user.Role == 1)
                    {
                        return RedirectToPage("/Admin/Dashboard");
                    }
                    return RedirectToPage("/UserMenu/ProductsMenu");
                }
            }
            else
            {
                ViewData["error"] = "Wrong username or password";
                return Page();
            }
        }

        public async Task<IActionResult> OnPostRegister()
        {
            try
            {
                string hashedPassword = BCrypt.Net.BCrypt.HashPassword(registerModel.Password);

                var user = new User
                {
                    FullName = registerModel.FullName,
                    UserName = registerModel.Username,
                    Email = registerModel.Email,
                    Phone = registerModel.Phone,
                    Password = hashedPassword,
                    Address = registerModel.Address,
                    Role = 2,
                    Status = 1
                };

                await _userService.AddUser(user);

                TempData["message"] = "Sign Up Successful";
                TempData["messageType"] = "success";

                return RedirectToPage("/Login");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception: {ex.Message}");
                TempData["message"] = "Please check you information, This information had already been used";
                TempData["messageType"] = "error";
                return RedirectToPage("/Login");
            }         
        }
    }
}

BabyStore/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BabyStore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

BabyStore/Pages/logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BabyStore.Pages
{
    public class logoutModel : PageModel
    {
        public async Task<IActionResult> OnGetAsync()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Login");
        }
    }
}

BabyStore/Pages/Login.cshtml
@page
@model BabyStore.Pages.AuthenModel
@{
    ViewData["Title"] = "Login | Baby Store";
    Layout = "~/Pages/Shared/_Layout_Login.cshtml";
    var message = TempData["message"] as string;
    var messageType = TempData["messageType"] as string;
}

<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        .toast {
            display: none;
            position: fixed;
            right: 20px;
            top: 20px;
            background-color: rgba(0, 0, 0, 0.8);
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            z-index: 1050
        }

        .toast-message {
            margin: 0;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }

        body {
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            background: #444;
        }

        .container {
            position: relative;
            width: 70vw;
            height: 80vh;
            background: #fff;
            border-radius: 15px;
            box-shadow: 0 4px 20px 0 rgba(0, 0, 0, 0.3), 0 6px 20px 0 rgba(0, 0, 0, 0.3);
            overflow: hidden;
        }

            .container::before {
                content: "";
                position: absolute;
                top: 0;
                left: -50%;
                width: 100%;
                height: 100%;
                background: linear-gradient(-45deg, #6699FF, #3399FF);
                z-index: 6;
                transform: translateX(100%);
                transition: 1s ease-in-out;
            }

        .signin-signup {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: space-around;
            z-index: 5;
        }

        form {
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            width: 40%;
            min-width: 238px;
            padding: 0 10px;
        }

            form.sign-in-form {
                opacity: 1;
                transition: 0.5s ease-in-out;
                transition-delay: 1s;
            }

            form.sign-up-form {
                opacity: 0;
                transition: 0.5s ease-in-out;
                transition-delay: 1s;
            }

        .title {
            font-size: 35px;
            color: #FF1493;
            margin-bottom: 10px;
        }

        .input-field {
            width: 100%;
            height: 50px;
            background: #f0f0f0;
            margin: 10px 0;
            border: 2px solid #FF1493;
            border-radius: 50px;
            display: flex;
            align-items: center;
        }

            .input-field i {
                flex: 1;
                text-align: center;
                color: #666;
                font-size: 18px;
            }

            .input-field input {
                flex: 5;
                background: none;
                border: none;
                outline: none;
                width: 100%;
                font-size: 18px;
                font-weight: 600;
                color: #444;
            }

        .btn {
            width: 150px;
            height: 50px;
            border: none;
            border-radius: 50px;
            background: #FF1493;
            color: #fff;
            font-weight: 600;
            margin: 10px 0;
            text-transform: uppercase;
            cursor: pointer;
        }

            .btn:hover {
                background: #FF69B4;
            }

        .social-text {
            margin: 10px 0;
            font-size: 16px;
        }

        .social-media {
            display: flex;
            justify-content: center;
        }

        .social-icon {
            height: 45px;
            width: 45px;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #444;
            border: 1px solid #444;
            border-radius: 50px;
            margin: 0 5px;
        }

        a {
            text-decoration: none;
        }

        .social-icon:hover {
            color: #df4adf;
            border-color: #df4adf;
        }

        .panels-container {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: space-around;
        }

        .panel {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: space-around;
            width: 35%;
            min-width: 238px;
            padding: 0 10px;
            text-align: center;
            z-index: 6;
        }

        .left-panel {
            pointer-events: none;
        }

        .content {
            color: black;
            transition: 1.1s ease-in-out;
            transition-delay: 0.5s;
        }

        .panel h3 {
            font-size: 24px;
            font-weight: 600;
        }

        .panel p {
            font-size: 15px;
            padding: 10px 0;
        }

        .image {
            width: 100%;
            transition: 1.1s ease-in-out;
            transition-delay: 0.4s;
        }

        .left-panel .image,
        .left-panel .content {
            transform: translateX(-200%);
        }

        .right-panel .image,
        .right-panel .content {
            transform: translateX(0);
        }

        .account-text {
            display: none;
        }
        /*Animation*/
        .container.sign-up-mode::before {
            transform: translateX(0);
        }

        .container.sign-up-mode .right-panel .image,
        .container.sign-up-mode .right-panel .content {
            transform: translateX(200%);
        }

        .container.sign-up-mode .left-panel .image,
        .container.sign-up-mode .left-panel .content {
            transform: translateX(0);
        }

        .container.sign-up-mode form.sign-in-form {
            opacity: 0;
        }

        .container.sign-up-mode form.sign-up-form {
            opacity: 1;
        }

        .container.sign-up-mode .right-panel {
            pointer-events: none;
        }

        .container.sign-up-mode .left-panel {
            pointer-events: all;
        }
    </style>
</head>
<body>
    <a href="/UserMenu/ProductsMenu" style="top: 0; left: 0; margin-top: 10px; margin-left: 10px; cursor: pointer;">
        <i class="material-icons" style="font-weight: 100; font-size: 50px; color: #FF1493">keyboard_backspace</i>
    </a>
    <div class="container">        
        <div class="signin-signup">
            <form method="post" class="sign-in-form" asp-page-handler="Login">
                <h2 class="title">Sign in</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" asp-for="loginModel.Username" placeholder="Username" required />
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" asp-for="loginModel.Password" placeholder="Password" autocomplete="new-password" required />
                </div>
                <div class="form-group text-danger">
                    @ViewData["error"]
                </div>
                <input type="submit" class="btn" value="Sign in">
                <p class="account-text">Don't have an account? <a href="#" id="sign-up-btn2">Sign up</a></p>
            </form>

            <form method="post" class="sign-up-form" asp-page-handler="Register">
                <h2 class="title">Sign up</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" asp-for="registerModel.FullName" placeholder="Fullname" required />
                </div>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" asp-for="registerModel.Username" placeholder="Username" required />
                </div>
                <div class="input-field">
                    <i class="fas fa-envelope"></i>
                    <input type="text" asp-for="registerModel.Email" placeholder="Email" required />
                </div>
                <div class="input-field">
                    <i class="fas fa-home"></i>
                    <input type="text" asp-for="registerModel.Address" placeholder="Address" required />
                </div>
                <div class="input-field">
                    <i class="fas fa-phone"></i>
                    <input type="number" asp-for="registerModel.Phone" placeholder="Phone" required />
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" asp-for="registerModel.Password" placeholder="Password" required />
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" asp-for="registerModel.ConfirmPassword" placeholder="Confirm Password" required />
                </div>
                <input type="submit" value="Sign up" class="btn">
                <p class="account-text">Already have an account? <a href="#" id="sign-in-btn2">Sign in</a></p>
            </form>
        </div>
        <div class="panels-container">
            <div class="panel left-panel">
                <div class="content">
                    <h3>Member of Store?</h3>
                    <p>Why not login right now and have a good shopping day</p>
                    <button class="btn" id="sign-in-btn">Sign in</button>
                </div>
                <img src="~/images/signin.png" alt="" class="image">
            </div>
            <div class="panel right-panel">
                <div class="content">
                    <h3>Want to buy golds for your baby?</h3>
                    <p>Register right now to buy new and custom clothes and more for mom and kids?</p>
                    <button class="btn" id="sign-up-btn">Sign up</button>
                </div>
                <img src="~/images/signup.png" alt="" class="image">
            </div>
        </div>
    </div>
    <div id="toast" class="toast">
        <div id="toastMessage" class="toast-message"></div>
    </div>

    <script>
        function showToast(message, type) {
            var toast = document.getElementById("toast");
            var toastMessage = document.getElementById("toastMessage");
            toastMessage.textContent = message;

            // Apply styles based on message type
            if (type === "success") {
                toast.style.backgroundColor = "green";
            } else if (type === "error") {
                toast.style.backgroundColor = "red";
            }

            toast.style.display = "block";

            setTimeout(function () {
                toast.style.display = "none";
            }, 3000); // Duration of 3 seconds
        }

        // Show toast if there are query parameters
        var message = "@message";
        var messageType = "@messageType";
        if (message) {
            showToast(message, messageType);
        }
    </script>
</body>
</html>

BabyStore/Pages/logout.cshtml
@page
@model BabyStore.Pages.logoutModel
@{
}